# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QSpinBox, QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(630, 439)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"background-color: rgb(115, 115, 115);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tab = QTabWidget(self.centralwidget)
        self.tab.setObjectName(u"tab")
        self.tab.setGeometry(QRect(10, 0, 611, 391))
        font = QFont()
        font.setPointSize(12)
        self.tab.setFont(font)
        self.tab.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tab.setTabPosition(QTabWidget.North)
        self.tab.setTabShape(QTabWidget.Triangular)
        self.tab.setElideMode(Qt.ElideMiddle)
        self.world_tab = QWidget()
        self.world_tab.setObjectName(u"world_tab")
        self.label_7 = QLabel(self.world_tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 40, 141, 41))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        font1.setBold(False)
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"background-color: rgb(0, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.world_tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 120, 141, 41))
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.world_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 200, 141, 41))
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"background-color: rgb(255, 87, 118);\n"
"color: rgb(0, 0, 0);")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.world_tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 280, 141, 41))
        self.label_10.setFont(font1)
        self.label_10.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.world_iran = QLabel(self.world_tab)
        self.world_iran.setObjectName(u"world_iran")
        self.world_iran.setGeometry(QRect(220, 40, 331, 41))
        font2 = QFont()
        font2.setFamilies([u"Seven Segment"])
        font2.setPointSize(30)
        font2.setBold(True)
        self.world_iran.setFont(font2)
        self.world_iran.setStyleSheet(u"color: rgb(0, 255, 127);")
        self.world_iran.setAlignment(Qt.AlignCenter)
        self.world_USA = QLabel(self.world_tab)
        self.world_USA.setObjectName(u"world_USA")
        self.world_USA.setGeometry(QRect(220, 120, 331, 41))
        self.world_USA.setFont(font2)
        self.world_USA.setStyleSheet(u"color: rgb(0, 255, 255);")
        self.world_USA.setAlignment(Qt.AlignCenter)
        self.world_germany = QLabel(self.world_tab)
        self.world_germany.setObjectName(u"world_germany")
        self.world_germany.setGeometry(QRect(220, 200, 331, 41))
        self.world_germany.setFont(font2)
        self.world_germany.setStyleSheet(u"color: rgb(255, 87, 118)")
        self.world_germany.setAlignment(Qt.AlignCenter)
        self.world_canad = QLabel(self.world_tab)
        self.world_canad.setObjectName(u"world_canad")
        self.world_canad.setGeometry(QRect(220, 280, 331, 41))
        self.world_canad.setFont(font2)
        self.world_canad.setStyleSheet(u"color: rgb(170, 170, 255);")
        self.world_canad.setAlignment(Qt.AlignCenter)
        self.tab.addTab(self.world_tab, "")
        self.alarm_tab = QWidget()
        self.alarm_tab.setObjectName(u"alarm_tab")
        self.gridLayoutWidget = QWidget(self.alarm_tab)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(40, 30, 531, 141))
        self.alarm_grid = QGridLayout(self.gridLayoutWidget)
        self.alarm_grid.setObjectName(u"alarm_grid")
        self.alarm_grid.setContentsMargins(0, 0, 0, 0)
        self.alarm_add = QPushButton(self.alarm_tab)
        self.alarm_add.setObjectName(u"alarm_add")
        self.alarm_add.setGeometry(QRect(470, 230, 81, 51))
        font3 = QFont()
        font3.setFamilies([u"Seven Segment"])
        font3.setPointSize(29)
        font3.setBold(False)
        self.alarm_add.setFont(font3)
        self.alarm_add.setStyleSheet(u"background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"")
        self.label_4 = QLabel(self.alarm_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 210, 91, 31))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.label_4.setFont(font4)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.alarm_tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 280, 91, 31))
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.alaram_hour = QSpinBox(self.alarm_tab)
        self.alaram_hour.setObjectName(u"alaram_hour")
        self.alaram_hour.setGeometry(QRect(180, 280, 91, 31))
        font5 = QFont()
        font5.setFamilies([u"Seven Segment"])
        font5.setPointSize(18)
        font5.setBold(True)
        self.alaram_hour.setFont(font5)
        self.alaram_hour.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.alaram_hour.setAlignment(Qt.AlignCenter)
        self.alaram_hour.setMaximum(23)
        self.alarm_minute = QSpinBox(self.alarm_tab)
        self.alarm_minute.setObjectName(u"alarm_minute")
        self.alarm_minute.setGeometry(QRect(320, 280, 91, 31))
        self.alarm_minute.setFont(font5)
        self.alarm_minute.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.alarm_minute.setAlignment(Qt.AlignCenter)
        self.alarm_minute.setMaximum(59)
        self.alarm_title = QLineEdit(self.alarm_tab)
        self.alarm_title.setObjectName(u"alarm_title")
        self.alarm_title.setGeometry(QRect(170, 200, 251, 41))
        font6 = QFont()
        font6.setPointSize(13)
        font6.setBold(True)
        self.alarm_title.setFont(font6)
        self.alarm_title.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.alarm_title.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.alarm_tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(280, 280, 21, 31))
        font7 = QFont()
        font7.setPointSize(16)
        font7.setBold(True)
        self.label_12.setFont(font7)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.alarm_tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 260, 49, 16))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.alarm_tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(340, 260, 49, 16))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.tab.addTab(self.alarm_tab, "")
        self.stop_tab = QWidget()
        self.stop_tab.setObjectName(u"stop_tab")
        self.stop_show = QLabel(self.stop_tab)
        self.stop_show.setObjectName(u"stop_show")
        self.stop_show.setGeometry(QRect(110, 60, 391, 81))
        font8 = QFont()
        font8.setFamilies([u"Seven Segment"])
        font8.setPointSize(40)
        font8.setBold(True)
        self.stop_show.setFont(font8)
        self.stop_show.setStyleSheet(u"color: rgb(170, 170, 255);")
        self.stop_show.setAlignment(Qt.AlignCenter)
        self.stop_stopbutton = QPushButton(self.stop_tab)
        self.stop_stopbutton.setObjectName(u"stop_stopbutton")
        self.stop_stopbutton.setGeometry(QRect(110, 220, 111, 41))
        self.stop_stopbutton.setFont(font5)
        self.stop_stopbutton.setStyleSheet(u"background-color: rgb(255, 87, 118);\n"
"color: rgb(0, 0, 0);")
        self.stop_startbutton = QPushButton(self.stop_tab)
        self.stop_startbutton.setObjectName(u"stop_startbutton")
        self.stop_startbutton.setGeometry(QRect(250, 220, 111, 41))
        self.stop_startbutton.setFont(font5)
        self.stop_startbutton.setStyleSheet(u"background-color: rgb(0, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.stop_resetbutton = QPushButton(self.stop_tab)
        self.stop_resetbutton.setObjectName(u"stop_resetbutton")
        self.stop_resetbutton.setGeometry(QRect(390, 220, 111, 41))
        self.stop_resetbutton.setFont(font5)
        self.stop_resetbutton.setStyleSheet(u"background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tab.addTab(self.stop_tab, "")
        self.timer_tab = QWidget()
        self.timer_tab.setObjectName(u"timer_tab")
        self.timer_hour = QLineEdit(self.timer_tab)
        self.timer_hour.setObjectName(u"timer_hour")
        self.timer_hour.setGeometry(QRect(120, 70, 91, 81))
        font9 = QFont()
        font9.setFamilies([u"Seven Segment"])
        font9.setPointSize(45)
        font9.setBold(True)
        self.timer_hour.setFont(font9)
        self.timer_hour.setStyleSheet(u"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color: rgb(170, 170, 255);")
        self.timer_hour.setAlignment(Qt.AlignCenter)
        self.timer_startbutton = QPushButton(self.timer_tab)
        self.timer_startbutton.setObjectName(u"timer_startbutton")
        self.timer_startbutton.setGeometry(QRect(250, 220, 111, 41))
        self.timer_startbutton.setFont(font5)
        self.timer_startbutton.setStyleSheet(u"background-color: rgb(0, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.timer_stopbutton = QPushButton(self.timer_tab)
        self.timer_stopbutton.setObjectName(u"timer_stopbutton")
        self.timer_stopbutton.setGeometry(QRect(110, 220, 111, 41))
        self.timer_stopbutton.setFont(font5)
        self.timer_stopbutton.setStyleSheet(u"background-color: rgb(255, 87, 118);\n"
"color: rgb(0, 0, 0);")
        self.timer_resetbutton = QPushButton(self.timer_tab)
        self.timer_resetbutton.setObjectName(u"timer_resetbutton")
        self.timer_resetbutton.setGeometry(QRect(390, 220, 111, 41))
        self.timer_resetbutton.setFont(font5)
        self.timer_resetbutton.setStyleSheet(u"background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.timer_minute = QLineEdit(self.timer_tab)
        self.timer_minute.setObjectName(u"timer_minute")
        self.timer_minute.setGeometry(QRect(260, 70, 91, 81))
        self.timer_minute.setFont(font9)
        self.timer_minute.setStyleSheet(u"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color: rgb(170, 170, 255);")
        self.timer_minute.setAlignment(Qt.AlignCenter)
        self.timer_second = QLineEdit(self.timer_tab)
        self.timer_second.setObjectName(u"timer_second")
        self.timer_second.setGeometry(QRect(400, 70, 91, 81))
        self.timer_second.setFont(font9)
        self.timer_second.setStyleSheet(u"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color: rgb(170, 170, 255);")
        self.timer_second.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.timer_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 40, 49, 16))
        font10 = QFont()
        font10.setPointSize(10)
        font10.setBold(True)
        self.label.setFont(font10)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.timer_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(280, 40, 49, 16))
        self.label_2.setFont(font10)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.timer_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 40, 49, 16))
        self.label_3.setFont(font10)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.timer_tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(360, 90, 21, 41))
        font11 = QFont()
        font11.setPointSize(21)
        font11.setBold(True)
        self.label_5.setFont(font11)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.timer_tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(220, 90, 21, 41))
        self.label_6.setFont(font11)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.tab.addTab(self.timer_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 630, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Clock", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Tehran, Iran", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Washington, U.S.A", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Berlin, Germany", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Ottawa, Canada", None))
        self.world_iran.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.world_USA.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.world_germany.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.world_canad.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.tab.setTabText(self.tab.indexOf(self.world_tab), QCoreApplication.translate("MainWindow", u"Wold Clock", None))
        self.alarm_add.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"title :", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"time :", None))
        self.alarm_title.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"hour", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"minute", None))
        self.tab.setTabText(self.tab.indexOf(self.alarm_tab), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.stop_show.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.stop_stopbutton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.stop_startbutton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stop_resetbutton.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tab.setTabText(self.tab.indexOf(self.stop_tab), QCoreApplication.translate("MainWindow", u"Stop Watch", None))
        self.timer_hour.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.timer_startbutton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.timer_stopbutton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.timer_resetbutton.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.timer_minute.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.timer_second.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"hour", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"minute", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"second", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tab.setTabText(self.tab.indexOf(self.timer_tab), QCoreApplication.translate("MainWindow", u"Timer", None))
    # retranslateUi

